# Generated by Django 4.2.3 on 2023-07-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0010_alter_position_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(default="Medium", max_length=6),
        ),
    ]
