# Generated by Django 4.2.3 on 2023-07-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_alter_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline', 'name', 'is_completed']},
        ),
    ]
