# Generated by Django 4.2.3 on 2023-07-21 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0020_alter_task_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                null=True, related_name="tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
